name = "PointProcesses"
uuid = "af0b7596-9bb0-472a-a012-63904f2b4c55"
authors = ["Guillaume Dalle"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
